### ISSUE TITLE
assignment 2 hand in by @GavinXing

### ISSUE THREAD

**Issue by GavinXing** [dyweb/course#10]
repo at https://github.com/GavinXing/web_homework/tree/assignment2

**Comment by GavinXing** [comment]
It seems like the link above failed......
repo at [https://github.com/GavinXing/web_homework/tree/assignment2](url)
please checkout the <assigment2> branch....

**Comment by GavinXing** [comment]
[www.baidu.com]()

**Comment by GavinXing** [comment]
how can I insert the url correctly....

**Comment by arrowrowe** [comment]
Just paste it like this: https://github.com/GavinXing/web_homework/tree/assignment2

``` markdown
https://github.com/GavinXing/web_homework/tree/assignment2
```

Or you may prefer [this](https://github.com/GavinXing/web_homework/tree/assignment2) done by

``` markdown
[this](https://github.com/GavinXing/web_homework/tree/assignment2)
```

Try [Mastering Markdown・GitHub Guides](https://guides.github.com/features/mastering-markdown/).

**Comment by GavinXing** [comment]
@arrowrowe So it doesn't need to use the {add a link} button....Thank you ~

**Comment by arrowrowe** [comment]
The :link: button does help in its own way, but you can always paste the url directly or enter markdown manually.

See also [Improved commenting with Markdown](https://github.com/blog/2097-improved-commenting-with-markdown).
