### ISSUE TITLE
read the docs domain change

### ISSUE THREAD

**Issue by at15** [dyweb/course#12]
hosted doc sub domain changes from `readthedocs.org` to `readthedocs.io` for preventing xss attack. So the links in slide, doc, readme should change as well. 

http://course.readthedocs.io/en/latest/

The blog post is here http://blog.readthedocs.com/securing-subdomains/
- [ ] master branch
- [ ] gh-pages branch

you can use PHPStorm to find string in path, or use ag cc @arrowrowe add the link for ag pls

**Comment by at15** [comment]
cc @arrowrowe guess we can assign this to some new guys?

**Comment by arrowrowe** [comment]
0.0

**Comment by at15** [comment]
@GavinXing @tripack45 @JasonQSY anyone?

**Comment by GavinXing** [comment]
The job is to change all of the links? @at15

**Comment by at15** [comment]
@GavinXing yep

**Comment by at15** [comment]
done, thanks to @GavinXing
