### ISSUE TITLE
Next week lecture 

### ISSUE THREAD

**Issue by at15** [dyweb/course#13]
The lecture for this week is canceled. We need to discuss what should be covered for next week's lecture. The topic is **HTTP and API Design**. I have listed some key points below.
- Computer networking lite. Layers, Physical, TCP, HTTP
- HTTP basic, verb, status code
- Dev tools, Chrome, curl, postman
- REST
- GraphQL

**Comment by at15** [comment]
cc @arrowrowe @ComMouse @LukeXuan

**Comment by ComMouse** [comment]
### Tutorial Resources for HTTP protocol & RESTful API
- [HTTP 教程](http://www.tutorialspoint.com/http/)
- [HTTP: The Protocol Every Web Developer Must Know Part I](http://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177)
- [HTTP: The Protocol Every Web Developer Must Know Part II](http://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-2--net-31155)
- [深入理解 HTTP 协议](http://www.360doc.com/content/10/0930/17/3668821_57590979.shtml)
- [RESTful API 设计指南](http://www.ruanyifeng.com/blog/2014/05/restful_api.html)
- [理解 RESTful 架构](http://www.ruanyifeng.com/blog/2011/09/restful.html)
- [REST API Tutorial](http://www.restapitutorial.com/)

**Comment by ComMouse** [comment]
http://open.163.com/special/opencourse/buildingdynamicwebsites.html

**Comment by at15** [comment]
I think I may not have time for next week's lecture ..... since my thesis project is way behind schedule ....

**Comment by ComMouse** [comment]
.......我来吧。。简直就是各种跳票啊。。以前讲过 REST 应该准备起来快一些

**Comment by at15** [comment]
@ComMouse /w\
