### ISSUE TITLE
Restful API Assignment Hand in

### ISSUE THREAD

**Issue by JasonQSY** [dyweb/course#20]
See the old repo https://github.com/JasonQSY/TodoList

A rough version.

**Comment by at15** [comment]
\w/

**Comment by at15** [comment]
I think someone should close all these issues? cc @ComMouse @JasonQSY

**Comment by JasonQSY** [comment]
Yeah.. Since @ComMouse will teach RESTful API again this Wednesday, may be we should close all the old issues last year.

**Comment by at15** [comment]
time flies and I am still single /w\

**Comment by LukeXuan** [comment]
single boy, single boy, single all the way
