### ISSUE TITLE
Homework hand in 

### ISSUE THREAD

**Issue by tripack45** [dyweb/course#8]
Repo Link: [tripack45/dyhw](https://github.com/tripack45/dyhw)
Testing Server: [Raspberry Pi 3](http://59.78.36.78:8080/hw1)

Homework1 is under "hw1" branch.
Implements Assignment I (ToDo-List) together with Assignment III (Simple Login).
Basically "Login Required Todo-List";
No SQL Injection protection, have fun!

Oh, I nearly forget @at15

**Comment by ComMouse** [comment]
LGTM, would you mind pasting your SQL file in your repo?

Also pay attention to code styling, here are some guidelines:
https://segmentfault.com/a/1190000002521620
https://segmentfault.com/a/1190000002521577

**Comment by at15** [comment]
\w/ (我在看番，先交给小豆了，逃

**Comment by tripack45** [comment]
@ComMouse You mean pasting the SQL database(the binary file) ? I thought you should only put up text files to GitHub. Sorry about the coding style. Re-factorization on the way.

**Comment by ComMouse** [comment]
No.... Just the SQL file..... You can use `mysqldump` to export the db file into sql script files.

**Comment by tripack45** [comment]
Done.

**Comment by ComMouse** [comment]
LGTM @at15

**Comment by arrowrowe** [comment]
:+1: 

btw sql injection?... @ComMouse e.g. password `1' or '1' = '1`...

**Comment by at15** [comment]
@arrowrowe I think we didn't mention that in course, but it would be nice if he knows how to use parameter binding etc. @tripack45  Though when in real projects, we use wrapped database classes, also known as ORM, ActiveRecord, which has built in support to prevent SQL injection if you use them properly. But for someone like @xsfour .... 

Ref:
- http://stackoverflow.com/questions/16282103/php-mysqli-prevent-sql-injection
- http://php.net/manual/en/mysqli-stmt.bind-param.php
- http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by at15** [comment]
I have made some comment in https://github.com/tripack45/dyhw/commit/a4f24e34f08d3448ec06ef474b6f2d394f8857fb cc @ComMouse @arrowrowe 

LGTM
