### ISSUE TITLE
Homework hand-in @GavinXing

### ISSUE THREAD

**Issue by ComMouse** [dyweb/course#9]
Repo at https://github.com/GavinXing/web_homework

Implements Assignment I.

@GavinXing

**Comment by at15** [comment]
e.... just one file?

**Comment by GavinXing** [comment]
@at15    the assignment asked to accomplish the task within 1 file.......I was willing to distribute it to several files.....

**Comment by arrowrowe** [comment]
@at15 See details for Assignment I [here](https://dyweb.github.io/course/web/2016_Spring/instant-php/slide.html#/ass1), as listed below:

> **ASSIGNMENT (I): Finish a simple To-do List application**
> - Only one file "todo.php" is enough
>   - Multiple files are also ok
> - Try to implement displaying, creating, editing & deleting of to-do items
> - No JS & CSS needed
>   - Just focus on PHP coding
> - (Advanced) Try to add file uploading in item creating form
>   - Tips: Use $_FILES superglobal

~~It says multiple files are ok /w\ @GavinXing~~

**Comment by GavinXing** [comment]
@at15 I have distribute todo.php into 3 files
@ComMouse I have just modified my code after your suggestion
Willing to hear from you more!
repo at [https://github.com/GavinXing/web_homework](url)

**Comment by at15** [comment]
@GavinXing I didn't look at the assignment requirement, sorry for that, I have posted some comment for the updated commit, you can have a look. And it seems you are not using IDE like phpstorm, what editor are u using? Anyway, pretty good work for someone who use php for the first time. :)

**Comment by GavinXing** [comment]
@at15  Now I use VScode after the first lecture. I will try phpstorm later~

**Comment by at15** [comment]
@GavinXing ok~

**Comment by GavinXing** [comment]
@ComMouse @at15 @arrowrowe I have add login logic in assignment 1.
Please check it~
For test, http://59.78.45.115:3333/ is okay.  login with 'user' '123456'
repo at  https://github.com/GavinXing/web_homework

**Comment by JasonQSY** [comment]
@GavinXing It seems that the server is broken, at least in my dorm. Not a big issue, though.

**Comment by GavinXing** [comment]
@JasonQSY Sorry, my server poweroff when I fold my labtop. I will start it when I return my dorm and let you know~

**Comment by JasonQSY** [comment]
@GavinXing I previously consider you use a server and something bad often happens when the server is broken. Since you use your laptop as the server, it does not matter and I can use localhost. Thank you and l learn a lot from your code.

**Comment by GavinXing** [comment]
@JasonQSY I have already start the server~

**Comment by at15** [comment]
@GavinXing you may get a phone call from http://net.sjtu.edu.cn/, which has happened to @gaocegege before, and they scan for vulnerable database password as well ......  I think I have mentioned this in the first lecture. 

btw: @tripack45 is using a Raspberry Pi 3, which @gaocegege also have but never use. (这么黑策策好么

**Comment by GavinXing** [comment]
@at15 You mean it's forbiddened to map my SJTU ip port to the server on my computer?

**Comment by gaocegege** [comment]
@GavinXing 你不用那种有名的端口就好了。之前我是用了3306，开了一个mysql，用了弱密码，之后被打电话了。室友用了80，也被打电话了。

现在在用树莓派，开了22的ssh端口，和一个5000端口，就一点事情没有(@at15 脸疼不疼

**Comment by at15** [comment]
@gaocegege 。。。反正是在学弟面前被打脸(反正也没有学妹

**Comment by GavinXing** [comment]
@gaocegege I used 3333.....At first I wanted to use 2333....

**Comment by GavinXing** [comment]
@gaocegege @at15 I suddenly find I mapped port 80 to my rpi.......I'm scared.....

**Comment by gaocegege** [comment]
@GavinXing 别虚，大不了就是一顿刚

**Comment by tripack45** [comment]
我表示直接把树莓派当做dmz主机全部暴露在外了。这样会有问题吗。

**Comment by GavinXing** [comment]
@tripack45 就映射几个端口出来吧？你树莓派搭了些什么呀，可以交流一下。。

**Comment by tripack45** [comment]
@GavinXing 目前就搭建了一个http服务器，Nginx。然后ssh和sftp这两个方便管理。地址见我的repo，tripack45/dyhw

**Comment by ComMouse** [comment]
感觉东岳可以卖 Web Hosting 业务了。。。@at15

**Comment by at15** [comment]
@ComMouse 我们还人均一台budgetvm 和阿里云 ....

**Comment by GavinXing** [comment]
@ComMouse @at15 @arrowrowe @JasonQSY @gaocegege 
I have make another version of ToDo List to distribute it on SinaCloud
repo at https://github.com/GavinXing/sinacloud
web link http://todolist.applinzi.com/
This website is roughly written. Help me.....

**Comment by tripack45** [comment]
好好玩了一把SQL注入。以及注册部分没有考虑用户名重名的问题。还有就是输入验证应该在服务端完成，不然对方可以伪造请求骗过Javascript

**Comment by at15** [comment]
@GavinXing @tripack45 peer review XD btw: @GavinXing  记得换头像，and @tripack45 头像是命运石之门的?

**Comment by arrowrowe** [comment]
re @at15 yep, [Suzuha](https://zh.moegirl.org/zh/%E9%98%BF%E4%B8%87%E9%9F%B3%E9%93%83%E7%BE%BD)'s father. (why don't i post his own link? cause moegirl.org does not have one for him :(...

**Comment by at15** [comment]
@arrowrowe \w/ 晚上记得namecheap续费dongyue.io .....

**Comment by tripack45** [comment]
Bug Report! 空用户名和密码竟然可以登录。以及各单引号都能登录
@at15 yep 这个是Super Hackar。

**Comment by at15** [comment]
@tripack45 刚看到第二集/w\ and bug label 已加

**Comment by at15** [comment]
@GavinXing your commit message is a good example for bad practice. ie https://github.com/GavinXing/sinacloud/commit/80adb3ab8ff904a0c6dd83e8583ad7eeaf85661c

**Comment by at15** [comment]
and @GavinXing @tripack45 @JasonQSY please visit https://github.com/dyweb to join the dyweb

**Comment by GavinXing** [comment]
@at15  I know my bad commits .... I should have tested on my own server...

**Comment by tripack45** [comment]
@GavinXing It's not what you COMMIT is bad, It'a about commit MESSAGES. notes you leave explaining your work. These notes are not clear enough. BTW how do you get hold of one of sina's hosting server? How much does it cost?

**Comment by GavinXing** [comment]
@tripack45 sina provides sae service which you can search "sina sae" for detail. Now I pay ¥0.5 everyday. It seems I don't make full use of the service I paid....

**Comment by JasonQSY** [comment]
@GavinXing Highly recommend DigitalOcean. With Github education, you can hire a simple server for 11 months with $5.

**Comment by GavinXing** [comment]
@JasonQSY Thank you for your recommendation~ I didn't know it before. $5 every 11months? A strange period

**Comment by JasonQSY** [comment]
@GavinXing Education discount gives you $50 for free. However, you need $5 to activate the service. The cheapest server is $5 per month. Sorry for my unclear conclusion.
